### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by biokys** [Ecetera/sbt-web-s3#1]
Hi, I am trying to use your library in PlayFramework 2.3 and it is not working because addSbtPlugin("au.com.ecetera.sbt" % "sbt-web-s3" % "0.1.0-SNAPSHOT") is not resolved. Didnt you change a version ????

**Comment by karlroberts** [comment]
Hi biokys, 
Yes I have changed the version number, I have not updated the doco yet, I'll do that now. Also I've not published this yet to a repo (so you have to build it yourself for now) as I need to write some tests before I call it a real release.
That said it does work. I've used it multiple times in the last week to upload static angular webapps to S3 :-)
I'll let you know when the new version of the docs have been pushed.

Thanks for the feedback,

**Comment by karlroberts** [comment]
Hi biokys,

I've updated the README  to reflect the current version and added more detail about the new tasks (eg s3wsSync and s3wsDeleteWhat) and the important new setting s3wsPrefix.

Please try again I'm sure it'll work for you now. Any questions please ask.

Cheers

Karl

**Comment by biokys** [comment]
Don't I need to add any dependency resolvers???

Error:Error while importing SBT project:
...
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error](*:update) sbt.ResolveException: unresolved dependency: au.com.ecetera.sbt#sbt-web-s3;0.2.1-SNAPSHOT: not found
Invalid response.

See complete log in /Users/muller/Library/Logs/IntelliJIdea14/sbt.last.log

**Comment by karlroberts** [comment]
As mentioned at the top of the README this plugin is not ready for production yet... the main reason is that I've not deployed it anywhere yet... so no resolver would work.

Instead for now if you want to try it you should build it locally and publish it to you local ivy repository (which is automatically searched by sbt)

follow the instructions at the end of the README ie checkit out from github then 

cd to into the directory that was created eg sbt-web-s3 and type :- make

that is equivilant to running 
$ ./sbt

> publishLocal

I intend to write a few tests this easter holiday, then I'll publish it to a real repository for general use.

hope that helps
